# Generated by Django 2.0.2 on 2018-02-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('username', models.CharField(default='�û�������Ϊ��', max_length=15)),
                ('password', models.CharField(default='���벻��Ϊ��', max_length=15)),
                ('kind', models.CharField(default=('PYTHON', 'PYTHON'), max_length=20)),
            ],
        ),
    ]
